[volume]
command=echo " $(~/.config/i3/scripts/volume.sh)"
label=
interval=1

[greetings]
color=#f5af19
command=echo "Uh oh, stinky!"
interval=once

# Date Time
#
[time]
command=date '+%Y-%m-%d %H:%M:%S'
interval=1

