(set-frame-font "Iosevka Light 12" nil t)
(load-theme 'atom-one-dark t)
(menu-bar-mode 0)
(tool-bar-mode 0)
(set-scroll-bar-mode nil)
(which-key-mode)
(projectile-mode +1)
(define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)
(define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
(ivy-mode 1)
(load-theme 'airline-onedark t)
(turn-on-page-break-lines-mode)
(dashboard-setup-startup-hook)
(global-display-line-numbers-mode)

(global-set-key [f8] 'neotree-toggle)

(add-hook 'after-init-hook 'global-company-mode)
(add-hook 'after-init-hook #'global-flycheck-mode)

(setq dashboard-banner-logo-title "Uh oh, stinky...")
(setq dashboard-items '((recents  . 5)
                        (bookmarks . 5)
                        (projects . 5)
                        (agenda . 5)
                        (registers . 5)))
(setq dashboard-startup-banner 3)
(setq dashboard-center-content t)
(setq neo-theme (if (display-graphic-p) 'icons 'arrow))

(setq c-default-style "linux")
(setq c-basic-offset 4)

(global-set-key (kbd "C-:") 'avy-goto-char)
(global-set-key (kbd "C-'") 'avy-goto-char-2)
(global-set-key (kbd "M-g f") 'avy-goto-line)
(global-set-key (kbd "M-g w") 'avy-goto-word-1)
(global-set-key (kbd "M-g e") 'avy-goto-word-0)
